---
title: "Model update"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
library(Hmisc)
library(rms)
library(glmnet)
library(tidyr)
library(dplyr)
library(purrr)
library(ROCit)
```

This notebook updates iteratively updates the base prognostic model applying recalibration, by adding additional lab variables in blocks of 3 days

```{r message=FALSE, cache=F}
source('./mdl-evaluation.R')
source('./mdl-selection.R')

num_imp <-100       # Number of multiple imputations
num_boot <- 200     # Number of bootstrap samples
random_seed <- 151  # Setting random seed for reproducibility

min_age <- 18       #  Minimum age for inclusion in analysis

max_cor -> 0.75     # Maximum correlation between variables to be included in model
```

```{r}
# Load the data, remove children, and transform Ct values into Z-scores

data <- read.csv('data.csv')
data <- data %>% filter(age >= min_age)
data <- data %>% filter(days > 0)

data$ct123 <- (data$ct123 - mean(data$ct123, na.rm=T))/sd(data$ct123, na.rm=T)
data$ct456 <- (data$ct456 - mean(data$ct456, na.rm=T))/sd(data$ct456, na.rm=T)

data
```

```{r}
# Construct the base prognostic model that only uses age and Ct in the first 48 hours

base_model <- function(df) {
  # Calculate the linear term in the logistic function of the model
  # p(x) = 1 / (1+exp(-lp(x))
  lp = with(df, 
            0.86215 - 
              0.05343*age + 
              3*10^-5*max(age - 5.0, 0)^3 - 
              6*10^-5*max(age - 30.0, 0)^3 + 
              3*10^-5*max(age - 58.0, 0)^3 - 
              0.8694*ct12)
  return(lp)
}
```

```{r}
# Add the logit contribution from the base model to the dataframe

vars0 <- c('out', 'age', 'ct12')
all_data0 <- data %>% select(all_of(vars0)) # This dataframe includes missing entries

lp0 <- unlist(map(1:nrow(all_data0), function(x) base_model(all_data0[x,])))
data['lp0'] <- lp0
data
```


```{r}
# Skip plot calibration and ROC plots of the base model (already done in notebook 2)

#mdl_folder0 <- "model-0"
#dir.create(mdl_folder0)

#data0 <- all_data0[complete.cases(all_data0),]

#pred0 <- unlist(map(1:nrow(data0), function(x) base_model(data0[x,]))) # prediction in log-odds (probabilities on logit scale)
#prob0 <- 1 / (1 + exp(-pred0))                                         # prediction as probability response

# Generate the data frame with the data needed for the calibration and ROC plots
#plot_data0 <- data.frame(out = data0$out, logodds = pred0, prob = prob0)

#cal_plot(base_model, plot_data0, "original", "prob", model_label = '', dir = mdl_folder0, fn = "cal_plot.pdf")
#roc_plot(data0$out, prob0, dir = mdl_folder0, fn = "roc_plot.pdf")
```

UPDATED MODEL FOR DAYS 1-2-3

```{r}
# Apply the Elastic Net variable selecion method on all the lab variables available for days 1-2-3

sat_imp_formula123 <- "~out + lp0 + alb123 + alt123 + ast123 + bun123 + ck123 + cre123 + crp123 + k123"

vars123 <- c('out', 'lp0', 'alb123', 'alt123', 'ast123', 'bun123', 'ck123', 'cre123', 'crp123', 'k123')
data123 <- data[complete.cases(data[, c('lp0')]),]
data123 <- data123 %>% filter(days > 0)
data123

sout123 <- selectVariables(random_seed, num_imp, sat_imp_formula123, data123, TRUE)

varf123 <- data.frame(unlist(sout123$names), unlist(sout123$counts))
names(varf123) <- c("Variable", "Freq")
varf123 <- varf123 %>% filter(Variable != "lp0" & Variable != "(Intercept)")
varf123
```

```{r}
# Apply threshold
day123_sel_thres <- 0.5
sel123 <- varf123 %>% filter(Freq > day123_sel_thres)
sel123
```

```{r}
cov123 <- cor(data123[,sel123$Variable], use='pairwise') > 0.75
cov123
```

```{r}
# Train the model for days 1-2-3 on the selected variables
mdl_vars123 <- append(sel123$Variable, 'lp0')
# mdl_vars123 <- mdl_vars123[! mdl_vars123 %in% c()] # Remove highly correlated variables
mdl_vars123

mdl_imp_formula123 <- "~out + lp0 + alb123 + alt123 + ast123 + bun123 + ck123 + cre123 + crp123 + k123"
mdl_lgr_formula123 <- paste('out', paste(mdl_vars123, collapse=" + "), sep=" ~ ")
mdl_lgr_formula123

mdl_folder123 <- "model-days123"
dir.create(mdl_folder123)

model123 <- generateModel(random_seed, num_imp, num_boot, 3, mdl_imp_formula123, mdl_lgr_formula123, data, mdl_vars123, mdl_folder123)

# Add the logit contribution from the model for days 1-2-3 to the dataframe
data['lp123'] <- predict(model123, data)
```

```{r}
# Generate the calibration and ROC plots for the models for days 1-2-3

vars <- append(mdl_vars123, 'out')
df <- data %>% select(all_of(vars))
full_data123 <- df[complete.cases(df),]
full_data123

pred123 <- predict(model123, full_data123) # prediction in log-odds (probabilities on logit scale)
probs123 <- 1 / (1 + exp(-pred123))  # prediction as probability response

# Generate the data frame with the data needed for the calibration and ROC plots
plot_data123 <- data.frame(out = full_data123$out, logodds = pred123, prob = probs123)

cal_plot(model123, plot_data123, "original", "prob", model_label = '', dir = mdl_folder123, fn = "cal_plot.pdf")
roc_plot(plot_data123$out, plot_data123$prob, dir = mdl_folder123, fn = "roc_plot.pdf")
```

UPDATED MODEL FOR DAYS 4-5-6

```{r}
# Apply the Elastic Net variable selecion method on all the lab variables available for days 4-5-6

sat_imp_formula456 <- "~out + lp123 + alb456 + alt456 + ast456 + bun456 + ck456 + cre456 + crp456 + k456"

vars456 <- c('out', 'lp123', 'alb456', 'alt456', 'ast456', 'bun456', 'ck456', 'cre456', 'crp456', 'k456')
data456 <- data[complete.cases(data[, c('lp123')]),]
data456 <- data456 %>% filter(days > 3)
data456

sout456 <- selectVariables(random_seed, num_imp, sat_imp_formula456, data456, TRUE)

varf456 <- data.frame(unlist(sout456$names), unlist(sout456$counts))
names(varf456) <- c("Variable", "Freq")
varf456 <- varf456 %>% filter(Variable != "lp123" & Variable != "(Intercept)")
varf456
```

```{r}
# Apply threshold
day456_sel_thres <- 0.5
sel456 <- varf456 %>% filter(Freq > day456_sel_thres)
sel456
```

```{r}
cov456 <- cor(data456[,sel456$Variable], use='pairwise') > 0.75
cov456
```

```{r}
# Train the model for days 4-5-6 on the selected variables
mdl_vars456 <- append(sel456$Variable, 'lp123')
mdl_vars456 <- mdl_vars456[! mdl_vars456 %in% c('bun456')] # Remove highly correlated variables
mdl_vars456

mdl_imp_formula456 <- "~out + lp123 + alb456 + alt456 + ast456 + bun456 + ck456 + cre456 + crp456 + k456"
mdl_lgr_formula456 <- paste('out', paste(mdl_vars456, collapse=" + "), sep=" ~ ")
mdl_lgr_formula456

mdl_folder456 <- "model-days456"
dir.create(mdl_folder456)

model456 <- generateModel(random_seed, num_imp, num_boot, 3, mdl_imp_formula456, mdl_lgr_formula456, data, mdl_vars456, mdl_folder456)

# Add the logit contribution from the model for days 4-5-6 to the dataframe
data['lp456'] <- predict(model456, data)
```

```{r}
# Generate the calibration and ROC plots for the models for days 4-5-6

vars <- append(mdl_vars456, 'out')
df <- data %>% select(all_of(vars))
full_data456 <- df[complete.cases(df),]
full_data456

pred456 <- predict(model456, full_data456) # prediction in log-odds (probabilities on logit scale)
probs456 <- 1 / (1 + exp(-pred456))  # prediction as probability response

# Generate the data frame with the data needed for the calibration and ROC plots
plot_data456 <- data.frame(out = full_data456$out, logodds = pred456, prob = probs456)

cal_plot(model456, plot_data456, "original", "prob", model_label = '', dir = mdl_folder456, fn = "cal_plot.pdf")
roc_plot(plot_data456$out, plot_data456$prob, dir = mdl_folder456, fn = "roc_plot.pdf")
```